<?php
/* 1. Service Landing Page */
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_597627ea33035',
		'title' => 'Landing page',
		'fields' => array (
			array (
				'key' => 'field_597627f700740',
				'label' => 'Problema',
				'name' => 'problem',
				'type' => 'text',
				'value' => NULL,
				'instructions' => 'Hai questo problema?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5976285a00741',
				'label' => 'Soluzione (Headline)',
				'name' => 'headline',
				'type' => 'text',
				'value' => NULL,
				'instructions' => 'Una breve descrizione della soluzione al problema. La “salvezza” dell\'utente. Dovrebbe contenere la parola chiave (keyword). In primo piano, al centro. Se è identica al Titolo, lascia il campo vuoto.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5976290d00743',
				'label' => 'Unique selling proposition (USP)',
				'name' => 'unique_selling_proposition',
				'type' => 'wysiwyg',
				'value' => NULL,
				'instructions' => 'L\'elemento di unicità che motiva all\'acquisto. La promessa. Una garanzia per l\'utente, meglio se con un elemento di unicità.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array (
				'key' => 'field_5976294100745',
				'label' => 'Immagine',
				'name' => 'image',
				'type' => 'text',
				'value' => NULL,
				'instructions' => 'ad es. /images/image.svg',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_597d9913bbb66',
				'label' => 'Introduzione alla CTA',
				'name' => 'before_cta',
				'type' => 'wysiwyg',
				'value' => NULL,
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array (
				'key' => 'field_5976292b00744',
				'label' => 'Call to action (CTA)',
				'name' => 'call_to_action',
				'type' => 'text',
				'value' => NULL,
				'instructions' => 'La chiamata all\'azione',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Richiedi <strong>maggiori informazioni</strong>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5976d2ad2c939',
				'label' => 'Introduzione al modulo (form)',
				'name' => 'before_form',
				'type' => 'wysiwyg',
				'value' => NULL,
				'instructions' => 'Un breve testo che spiega l’obiettivo del modulo e cosa succederà dopo l’invio.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array (
				'key' => 'field_59ae79f8619f7',
				'label' => 'Form',
				'name' => 'form_path',
				'type' => 'text',
				'value' => NULL,
				'instructions' => 'Inserisci il path per <code>get_template_part()</code>. Ad es. template-parts/form/basic_contacts',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'template-parts/form/basic_contacts',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => $frontpage_id,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'servizi',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;
?>