<?php
/* 1. Locations
 * 1.1. Fiscal Data
 * 1.2. Contacts and Opening Hours
 * 1.3. Location Privacy
 */
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_59cdf341041c6',
		'title' => 'Dati fiscali',
		'fields' => array(
			array(
				'key' => 'field_59cdf36a04e29',
				'label' => 'Ragione sociale',
				'name' => 'legalName',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59cdf9d504e2a',
				'label' => 'Codice fiscale',
				'name' => 'taxID',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59cdf9ef04e2b',
				'label' => 'Partita IVA',
				'name' => 'vatID',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59cdfa7e8c35b',
				'label' => 'Sede legale',
				'name' => 'legalAddress',
				'type' => 'google_map',
				'instructions' => 'Indicare solo se diversa dall\'indirizzo specificato nella sezione “Contatti e Orari di apertura”.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'sedi',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59ce6741f0b74',
		'title' => 'Contatti e Orari di apertura',
		'fields' => array (
			array (
				'key' => 'field_59d3ae20c4aa9',
				'label' => 'Nome breve',
				'name' => 'name',
				'type' => 'text',
				'value' => NULL,
				'instructions' => 'Ad es. Roma',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ce689617981',
				'label' => 'Indirizzo postale',
				'name' => 'address',
				'type' => 'google_map',
				'value' => NULL,
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
			array (
				'key' => 'field_59e06c3a810cd',
				'label' => 'Url Mappa',
				'name' => 'hasmap',
				'type' => 'text',
				'value' => NULL,
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59d39f0602e15',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'value' => NULL,
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_59e0769e61661',
				'label' => 'Contatti telefonici',
				'name' => 'contactPoints',
				'type' => 'repeater',
				'value' => NULL,
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => '',
				'sub_fields' => array (
					array (
						'key' => 'field_59e0769e61662',
						'label' => 'Numero di telefono',
						'name' => 'telephone',
						'type' => 'text',
						'value' => NULL,
						'instructions' => 'Il numero di telefono formattato, ad es. +39 800 1234 123',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_59e0769e61663',
						'label' => 'Tipo di contatto',
						'name' => 'contactType',
						'type' => 'checkbox',
						'value' => NULL,
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'customer support' => 'servizio clienti',
							'technical support' => 'assistenza tecnica',
							'billing support' => 'supporto alla fatturazione',
							'bill payment' => 'pagamento fatture',
							'sales' => 'vendite',
							'reservations' => 'prenotazioni',
							'credit card support' => 'supporto carte di credito',
							'emergency' => 'emergenze',
							'baggage tracking' => 'tracciamento bagagli',
							'roadside assistance' => 'assistenza stradale',
							'package tracking' => 'tracciamento spedizioni',
						),
						'allow_custom' => 0,
						'save_custom' => 0,
						'default_value' => array (
						),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
					),
					array (
						'key' => 'field_59e0769e61664',
						'label' => 'Opzioni di contatto',
						'name' => 'contactOption',
						'type' => 'text',
						'value' => NULL,
						'instructions' => 'Ad es. Numero verde',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_59e0769e61665',
						'label' => 'Aree servite',
						'name' => 'areaServed',
						'type' => 'text',
						'value' => NULL,
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array (
				'key' => 'field_59d39f1c56ee1',
				'label' => 'Fax',
				'name' => 'faxNumber',
				'type' => 'text',
				'value' => NULL,
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59d39f304f5b4',
				'label' => 'Orari di apertura',
				'name' => 'openingHours',
				'type' => 'textarea',
				'value' => NULL,
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array (
				'key' => 'field_59e06d3fc5db4',
				'label' => 'Google Place ID',
				'name' => 'google_place_id',
				'type' => 'text',
				'value' => NULL,
				'instructions' => '<a href="https://developers.google.com/places/place-id" target="_blank">Trova il Google place ID</a>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'sedi',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_59d3c408d827e',
		'title' => 'Privacy per la sede',
		'fields' => array(
			array(
				'key' => 'field_59d3c4195f13e',
				'label' => 'Responsabile Privacy',
				'name' => 'privacyResponsible',
				'type' => 'user',
				'instructions' => 'Selezionare tra gli <a href="/wp-admin/users.php">Utenti</a> il responsabile per la Privacy per questa sede.<br />
	<a href="/wp-admin/user-new.php">Aggiungi un nuovo Utente</a>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'role' => array(
					0 => 'administrator',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'sedi',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
endif;
?>